services:
  frontend:
    build: ./Control_System
    container_name: control-frontend
    ports:
      - "3001:3001"
    restart: unless-stopped

  backend:
    build: ./fastapi-starter
    container_name: control-backend
    network_mode: host
    volumes:
      - ./fastapi-starter/data:/app/data
    restart: unless-stopped
