services:
  frontend:
    build: ./Frontend
    container_name: control-frontend
    ports:
      - "3001:3001"
    restart: unless-stopped

  backend:
    build: ./Backend
    container_name: control-backend
    network_mode: host
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./Backend/data:/app/data
      - ./Backend/static:/app/static
    restart: unless-stopped
